# Server配置
server:
  port: 2000

# Spring配置
spring:
  profiles:
    active: test
  main:
    allow-circular-references: true

# 日志配置
logging:
  level:
    com.example.yugi: debug

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml  # mapper文件路径
  configuration:
    map-underscore-to-camel-case: true                # 驼峰与下划线转换

# PageHelper配置
pagehelper:
  helperDialect: mysql


