server.port=2000

spring.datasource.url=jdbc:mysql://10.2.0.55:3306/odms?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=tddprerelease
spring.datasource.password=8.zBsj540gB9o-ht1)x6c-NR_+^E25Jj)gAj^+Ma4#5tM1#Q=1JrrU9thRVrdMdL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
